### MSCI Indices

In [31]:
import pandas as pd

fname_prefix = "US_indices/MSCI USA Quality GARP Select Index"
df = pd.read_excel(f"{fname_prefix}.xlsx", skiprows=5, usecols=[0,1])
df.to_csv(f"{fname_prefix}.csv", index=False)
df.tail()

            Date  MSCI USA Quality GARP Select Index
6084  2026-03-26                         1262.294497
6085  2026-03-27                         1238.391818
6086  2026-03-30                         1221.898122
6087  2026-03-31                         1270.282184
6088  2026-04-01                         1285.859959

### RAFI Indices

In [2]:
import pandas as pd

df = pd.read_excel(f"US_indices/RAFI-US-Returns.xlsx", skiprows=9)
df = df.iloc[:, 1:]
df.head()

,Unnamed: 1,RAFI Dynamic Multi-Factor US Index,Unnamed: 3,Unnamed: 4,RAFI Fundamental High Liquidity US All Index,Unnamed: 6,Unnamed: 7,RAFI Fundamental High Liquidity US Large Index,Unnamed: 9,Unnamed: 10,RAFI Fundamental US Index,Unnamed: 12,Unnamed: 13,RAFI Fundamental Select US 1000 Index,Unnamed: 15,Unnamed: 16
0,NaN,RADMFUST,NaN,NaN,RAHLUSAT,NaN,NaN,RAHLUSLT,NaN,NaN,RAFIUST,NaN,NaN,RAFSUSLT,NaN,NaN
1,Date,Total Returns,Net Returns,Price Returns,Total Returns,Net Returns,Price Returns,Total Returns,Net Returns,Price Returns,Total Returns,Net Returns,Price Returns,Total Returns,Net Returns,Price Returns
2,2026-03-30 00:00:00,-0.006661,-0.006662,-0.006667,-0.002977,-0.002979,-0.002989,-0.002657,-0.002655,-0.002671,-0.002328,-0.00233,-0.002338,-0.002729,-0.002743,-0.00275
3,2026-03-27 00:00:00,-0.009705,-0.009711,-0.009729,-0.011345,-0.011356,-0.01138,-0.01104,-0.011057,-0.011078,-0.012272,-0.01228,-0.012304,-0.012663,-0.012678,-0.012697
4,2026-03-26 00:00:00,-0.012396,-0.0124,-0.012411,-0.007912,-0.007915,-0.007924,-0.007495,-0.007494,-0.007494,-0.009032,-0.009033,-0.009034,-0.009326,-0.009323,-0.009333

In [2]:
date_col = df.iloc[2:,0]

indices = []
for col in df.columns[1:]:
    if col.__contains__("Index"):
        indices.append(col)
indices

['RAFI Dynamic Multi-Factor US Index',
 'RAFI Fundamental High Liquidity US All Index',
 'RAFI Fundamental High Liquidity US Large Index',
 'RAFI Fundamental US Index',
 'RAFI Fundamental Select US 1000 Index']

In [3]:
df = df.loc[2:, indices]
df.index = date_col
df.index.name = 'Date'
df.head()

for i in range(len(indices)):
    df[indices[i]].dropna().to_csv(f"{indices[i]}.csv", index=True)

/Users/abhilaksh/anaconda3/lib/python3.13/site-packages/pandas/core/indexes/base.py:7631: FutureWarning: Dtype inference on a pandas object (Series, Index, ExtensionArray) is deprecated. The Index constructor will keep the original dtype in the future. Call `infer_objects` on the result to get the old behavior.
  return Index(index_like, name=name, copy=copy)

In [54]:
df[indices[2]][df[indices[2]] == 0]

Date
2024-05-01    0
2024-02-13    0
2024-02-12    0
2024-01-01    0
2023-12-25    0
2023-05-01    0
2023-04-07    0
2023-01-02    0
2022-05-02    0
2022-04-15    0
2021-04-02    0
2020-12-25    0
2020-05-01    0
2020-04-10    0
2020-01-01    0
2019-12-25    0
2019-05-01    0
2019-04-19    0
2018-12-25    0
2018-05-01    0
2017-12-25    0
2017-05-01    0
2017-01-02    0
2016-05-02    0
2016-02-08    0
2015-05-01    0
2014-05-01    0
2013-05-01    0
2013-03-31    0
2012-05-01    0
2011-05-02    0
2010-02-15    0
2009-05-01    0
2009-01-26    0
2008-05-01    0
2007-05-01    0
2007-02-19    0
2006-05-01    0
2003-05-01    0
2002-05-01    0
2002-03-31    0
2002-02-12    0
2001-05-01    0
2001-01-25    0
2000-12-25    0
2000-05-01    0
2000-01-03    0
1998-05-01    0
1998-01-02    0
1997-05-01    0
1996-05-01    0
Name: RAFI Fundamental Select Emerging Markets 350 Index, dtype: object